// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"runtime/trace"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/pkg/errors"
)

const (
	Jwt_tokenScopes = "jwt_token.Scopes"
)

// ClaimTokenId defines model for ClaimTokenId.
type ClaimTokenId struct {

	// Unix Epoch in seconds
	ExpiresAt int64  `json:"expires_at"`
	TokenId   string `json:"token_id"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	AccessKeyId string `json:"access_key_id"`

	// Unix Epoch in seconds
	CreationDate int64 `json:"creation_date"`

	// True if this access key is restricted to read-only operations.
	ReadOnly *bool `json:"read_only,omitempty"`
}

// CredentialsList defines model for CredentialsList.
type CredentialsList struct {

	// The pagination mechanism is used to retrieve a list of items.
	Pagination Pagination    `json:"pagination"`
	Results    []Credentials `json:"results"`
}

// CredentialsWithSecret defines model for CredentialsWithSecret.
type CredentialsWithSecret struct {
	AccessKeyId string `json:"access_key_id"`

	// Unix Epoch in seconds.
	CreationDate int64 `json:"creation_date"`

	// True if this access key is restricted to read-only operations.
	ReadOnly        *bool  `json:"read_only,omitempty"`
	SecretAccessKey string `json:"secret_access_key"`
	UserId          int64  `json:"user_id"`

	// Important - this filed is required instead of the user_id which is deprecated. A unique identifier for the user. In password-based authentication should be the email.
	UserName *string `json:"user_name,omitempty"`
}

// Error defines model for Error.
type Error struct {

	// The error message.
	Message string `json:"message"`
}

// ExternalPrincipal defines model for ExternalPrincipal.
type ExternalPrincipal struct {
	Id     string `json:"id"`
	UserId string `json:"user_id"`
}

// ExternalPrincipalList defines model for ExternalPrincipalList.
type ExternalPrincipalList struct {

	// The pagination mechanism is used to retrieve a list of items.
	Pagination Pagination          `json:"pagination"`
	Results    []ExternalPrincipal `json:"results"`
}

// Group defines model for Group.
type Group struct {

	// Unix Epoch in seconds.
	CreationDate int64   `json:"creation_date"`
	Description  *string `json:"description,omitempty"`

	// A unique identifier of the group.
	Id *string `json:"id,omitempty"`

	// A unique identifier for the group, represented by a human-readable name.
	Name string `json:"name"`
}

// GroupCreation defines model for GroupCreation.
type GroupCreation struct {
	Description *string `json:"description,omitempty"`

	// A unique identifier for the group, represented by a human-readable name.
	Id string `json:"id"`
}

// GroupList defines model for GroupList.
type GroupList struct {

	// The pagination mechanism is used to retrieve a list of items.
	Pagination Pagination `json:"pagination"`
	Results    []Group    `json:"results"`
}

// Pagination defines model for Pagination.
type Pagination struct {

	// A boolean indicating whether the Next page is available.
	HasMore bool `json:"has_more"`

	// Maximum number of entries per page.
	MaxPerPage int `json:"max_per_page"`

	// A value used to retrieve the next page of results. This value is typically passed as the after parameter in the subsequent API call. The next page will include all items appearing after the specified next_offset.
	NextOffset string `json:"next_offset"`

	// Number of values in the results.
	Results int `json:"results"`
}

// Policy defines model for Policy.
type Policy struct {

	// Represents the access control list assigned to this policy.
	Acl *string `json:"acl,omitempty"`

	// Unix Epoch in seconds.
	CreationDate *int64 `json:"creation_date,omitempty"`

	// A unique, human-readable name for the policy.
	Name      string      `json:"name"`
	Statement []Statement `json:"statement"`
}

// PolicyCondition defines model for PolicyCondition.
type PolicyCondition struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// PolicyList defines model for PolicyList.
type PolicyList struct {

	// The pagination mechanism is used to retrieve a list of items.
	Pagination Pagination `json:"pagination"`
	Results    []Policy   `json:"results"`
}

// Statement defines model for Statement.
type Statement struct {
	Action []string `json:"action"`

	// Optional conditions for when this statement applies.
	Condition *Statement_Condition `json:"condition,omitempty"`
	Effect    string               `json:"effect"`
	Resource  string               `json:"resource"`
}

// Statement_Condition defines model for Statement.Condition.
type Statement_Condition struct {
	AdditionalProperties map[string]PolicyCondition `json:"-"`
}

// User defines model for User.
type User struct {

	// Unix Epoch in seconds.
	CreationDate int64   `json:"creation_date"`
	Email        *string `json:"email,omitempty"`

	// Represents an encrypted password as a string.
	EncryptedPassword []byte  `json:"encryptedPassword"`
	ExternalId        *string `json:"external_id,omitempty"`

	// A name for the user that is not necessarily unique.
	FriendlyName *string `json:"friendly_name,omitempty"`

	// User source. Based on implementation.
	Source *string `json:"source,omitempty"`

	// A unique identifier for the user.
	Username string `json:"username"`
}

// UserCreation defines model for UserCreation.
type UserCreation struct {

	// If provided, the email is set to the same value as the username.
	Email *string `json:"email,omitempty"`

	// Represents an encrypted password as a string.
	EncryptedPassword *[]byte `json:"encryptedPassword,omitempty"`
	ExternalId        *string `json:"external_id,omitempty"`
	FriendlyName      *string `json:"friendlyName,omitempty"`

	// A boolean that determines whether an invitation email should be sent to a user for account creation. If passed and set to true, the invitation email will be sent along with the user creation.
	Invite *bool `json:"invite,omitempty"`

	// User source. Based on implementation.
	Source *string `json:"source,omitempty"`

	// A unique identifier for the user. For password-based authentication, it is the email.
	Username string `json:"username"`
}

// UserList defines model for UserList.
type UserList struct {

	// The pagination mechanism is used to retrieve a list of items.
	Pagination Pagination `json:"pagination"`
	Results    []User     `json:"results"`
}

// UserPassword defines model for UserPassword.
type UserPassword struct {
	EncryptedPassword []byte `json:"encryptedPassword"`
}

// VersionConfig defines model for VersionConfig.
type VersionConfig struct {
	Version string `json:"version"`
}

// PaginationAfter defines model for PaginationAfter.
type PaginationAfter string

// PaginationAmount defines model for PaginationAmount.
type PaginationAmount int

// PaginationPrefix defines model for PaginationPrefix.
type PaginationPrefix string

// Conflict defines model for Conflict.
type Conflict Error

// NotFound defines model for NotFound.
type NotFound Error

// ServerError defines model for ServerError.
type ServerError Error

// Unauthorized defines model for Unauthorized.
type Unauthorized Error

// ValidationError defines model for ValidationError.
type ValidationError Error

// GetExternalPrincipalParams defines parameters for GetExternalPrincipal.
type GetExternalPrincipalParams struct {
	PrincipalId string `json:"principalId"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// CreateGroupJSONBody defines parameters for CreateGroup.
type CreateGroupJSONBody GroupCreation

// ListGroupMembersParams defines parameters for ListGroupMembers.
type ListGroupMembersParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// ListGroupPoliciesParams defines parameters for ListGroupPolicies.
type ListGroupPoliciesParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// ListPoliciesParams defines parameters for ListPolicies.
type ListPoliciesParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// CreatePolicyJSONBody defines parameters for CreatePolicy.
type CreatePolicyJSONBody Policy

// UpdatePolicyJSONBody defines parameters for UpdatePolicy.
type UpdatePolicyJSONBody Policy

// ClaimTokenIdJSONBody defines parameters for ClaimTokenId.
type ClaimTokenIdJSONBody ClaimTokenId

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
	Id     *int64            `json:"id,omitempty"`
	Email  *string           `json:"email,omitempty"`

	// Used only in lakeFS Enterprise; not applicable in the lakeFS OSS version.
	ExternalId *string `json:"external_id,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody UserCreation

// ListUserCredentialsParams defines parameters for ListUserCredentials.
type ListUserCredentialsParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// CreateCredentialsParams defines parameters for CreateCredentials.
type CreateCredentialsParams struct {
	AccessKey *string `json:"access_key,omitempty"`
	SecretKey *string `json:"secret_key,omitempty"`

	// If true, the new access key can only perform read operations.
	ReadOnly *bool `json:"read_only,omitempty"`
}

// DeleteUserExternalPrincipalParams defines parameters for DeleteUserExternalPrincipal.
type DeleteUserExternalPrincipalParams struct {
	PrincipalId string `json:"principalId"`
}

// CreateUserExternalPrincipalParams defines parameters for CreateUserExternalPrincipal.
type CreateUserExternalPrincipalParams struct {
	PrincipalId string `json:"principalId"`
}

// ListUserExternalPrincipalsParams defines parameters for ListUserExternalPrincipals.
type ListUserExternalPrincipalsParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// UpdateUserFriendlyNameJSONBody defines parameters for UpdateUserFriendlyName.
type UpdateUserFriendlyNameJSONBody struct {
	FriendlyName string `json:"friendly_name"`
}

// ListUserGroupsParams defines parameters for ListUserGroups.
type ListUserGroupsParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`
}

// UpdatePasswordJSONBody defines parameters for UpdatePassword.
type UpdatePasswordJSONBody UserPassword

// ListUserPoliciesParams defines parameters for ListUserPolicies.
type ListUserPoliciesParams struct {

	// Indicates the prefix that all returned items must start with for the purpose of filtering results.
	Prefix *PaginationPrefix `json:"prefix,omitempty"`

	// Indicates the starting point for the returned items. Items must be sorted by a specific parameter, and the response should include only those that come after the "after" value in the sorted list. This is used for pagination, as the next page needs to start from a specific point in the ordered items list.
	After *PaginationAfter `json:"after,omitempty"`

	// Specifies the number of items the server should return. It is used to determine how many results to display.
	Amount *PaginationAmount `json:"amount,omitempty"`

	// If true, return all distinct policies attached to the user or any of the groups the user belongs to, otherwise, return only the policies directly attached to the user.
	Effective *bool `json:"effective,omitempty"`
}

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody CreateGroupJSONBody

// CreatePolicyJSONRequestBody defines body for CreatePolicy for application/json ContentType.
type CreatePolicyJSONRequestBody CreatePolicyJSONBody

// UpdatePolicyJSONRequestBody defines body for UpdatePolicy for application/json ContentType.
type UpdatePolicyJSONRequestBody UpdatePolicyJSONBody

// ClaimTokenIdJSONRequestBody defines body for ClaimTokenId for application/json ContentType.
type ClaimTokenIdJSONRequestBody ClaimTokenIdJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserFriendlyNameJSONRequestBody defines body for UpdateUserFriendlyName for application/json ContentType.
type UpdateUserFriendlyNameJSONRequestBody UpdateUserFriendlyNameJSONBody

// UpdatePasswordJSONRequestBody defines body for UpdatePassword for application/json ContentType.
type UpdatePasswordJSONRequestBody UpdatePasswordJSONBody

// Getter for additional properties for PolicyCondition. Returns the specified
// element and whether it was found
func (a PolicyCondition) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PolicyCondition
func (a *PolicyCondition) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PolicyCondition to handle AdditionalProperties
func (a *PolicyCondition) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PolicyCondition to handle AdditionalProperties
func (a PolicyCondition) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Statement_Condition. Returns the specified
// element and whether it was found
func (a Statement_Condition) Get(fieldName string) (value PolicyCondition, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Statement_Condition
func (a *Statement_Condition) Set(fieldName string, value PolicyCondition) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]PolicyCondition)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Statement_Condition to handle AdditionalProperties
func (a *Statement_Condition) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]PolicyCondition)
		for fieldName, fieldBuf := range object {
			var fieldVal PolicyCondition
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Statement_Condition to handle AdditionalProperties
func (a Statement_Condition) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// chi-interface.tmpl based on https://github.com/deepmap/oapi-codegen/tree/master/pkg/codegen/templates

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get credentials
	// (GET /auth/credentials/{accessKeyId})
	GetCredentials(w http.ResponseWriter, r *http.Request, accessKeyId string)
	// describe external principal by id
	// (GET /auth/external/principals)
	GetExternalPrincipal(w http.ResponseWriter, r *http.Request, params GetExternalPrincipalParams)
	// list groups
	// (GET /auth/groups)
	ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams)
	// create group
	// (POST /auth/groups)
	CreateGroup(w http.ResponseWriter, r *http.Request, body CreateGroupJSONRequestBody)
	// delete group
	// (DELETE /auth/groups/{groupId})
	DeleteGroup(w http.ResponseWriter, r *http.Request, groupId string)
	// get group
	// (GET /auth/groups/{groupId})
	GetGroup(w http.ResponseWriter, r *http.Request, groupId string)
	// list group members
	// (GET /auth/groups/{groupId}/members)
	ListGroupMembers(w http.ResponseWriter, r *http.Request, groupId string, params ListGroupMembersParams)
	// delete group membership
	// (DELETE /auth/groups/{groupId}/members/{userId})
	DeleteGroupMembership(w http.ResponseWriter, r *http.Request, groupId string, userId string)
	// add group membership
	// (PUT /auth/groups/{groupId}/members/{userId})
	AddGroupMembership(w http.ResponseWriter, r *http.Request, groupId string, userId string)
	// list group policies
	// (GET /auth/groups/{groupId}/policies)
	ListGroupPolicies(w http.ResponseWriter, r *http.Request, groupId string, params ListGroupPoliciesParams)
	// detach policy from group
	// (DELETE /auth/groups/{groupId}/policies/{policyId})
	DetachPolicyFromGroup(w http.ResponseWriter, r *http.Request, groupId string, policyId string)
	// attach policy to group
	// (PUT /auth/groups/{groupId}/policies/{policyId})
	AttachPolicyToGroup(w http.ResponseWriter, r *http.Request, groupId string, policyId string)
	// list policies
	// (GET /auth/policies)
	ListPolicies(w http.ResponseWriter, r *http.Request, params ListPoliciesParams)
	// create policy
	// (POST /auth/policies)
	CreatePolicy(w http.ResponseWriter, r *http.Request, body CreatePolicyJSONRequestBody)
	// delete policy
	// (DELETE /auth/policies/{policyId})
	DeletePolicy(w http.ResponseWriter, r *http.Request, policyId string)
	// get policy
	// (GET /auth/policies/{policyId})
	GetPolicy(w http.ResponseWriter, r *http.Request, policyId string)
	// update policy
	// (PUT /auth/policies/{policyId})
	UpdatePolicy(w http.ResponseWriter, r *http.Request, body UpdatePolicyJSONRequestBody, policyId string)
	// claim a token ID, returns validation error if already claimed
	// (POST /auth/tokenid/claim)
	ClaimTokenId(w http.ResponseWriter, r *http.Request, body ClaimTokenIdJSONRequestBody)
	// list users
	// (GET /auth/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// create user
	// (POST /auth/users)
	CreateUser(w http.ResponseWriter, r *http.Request, body CreateUserJSONRequestBody)
	// delete user
	// (DELETE /auth/users/{userId})
	DeleteUser(w http.ResponseWriter, r *http.Request, userId string)
	// get user
	// (GET /auth/users/{userId})
	GetUser(w http.ResponseWriter, r *http.Request, userId string)
	// list user credentials
	// (GET /auth/users/{userId}/credentials)
	ListUserCredentials(w http.ResponseWriter, r *http.Request, userId string, params ListUserCredentialsParams)
	// create credentials
	// (POST /auth/users/{userId}/credentials)
	CreateCredentials(w http.ResponseWriter, r *http.Request, userId string, params CreateCredentialsParams)
	// delete credentials
	// (DELETE /auth/users/{userId}/credentials/{accessKeyId})
	DeleteCredentials(w http.ResponseWriter, r *http.Request, userId string, accessKeyId string)
	// get credentials for a user
	// (GET /auth/users/{userId}/credentials/{accessKeyId})
	GetCredentialsForUser(w http.ResponseWriter, r *http.Request, userId string, accessKeyId string)
	// delete external principal from user's external principal list
	// (DELETE /auth/users/{userId}/external/principals)
	DeleteUserExternalPrincipal(w http.ResponseWriter, r *http.Request, userId string, params DeleteUserExternalPrincipalParams)
	// Create principal as external identity connected to a user
	// (POST /auth/users/{userId}/external/principals)
	CreateUserExternalPrincipal(w http.ResponseWriter, r *http.Request, userId string, params CreateUserExternalPrincipalParams)
	// list external principals for user
	// (GET /auth/users/{userId}/external/principals/ls)
	ListUserExternalPrincipals(w http.ResponseWriter, r *http.Request, userId string, params ListUserExternalPrincipalsParams)
	// update users friendly name
	// (PUT /auth/users/{userId}/friendly_name)
	UpdateUserFriendlyName(w http.ResponseWriter, r *http.Request, body UpdateUserFriendlyNameJSONRequestBody, userId string)
	// list user groups
	// (GET /auth/users/{userId}/groups)
	ListUserGroups(w http.ResponseWriter, r *http.Request, userId string, params ListUserGroupsParams)
	// update users password
	// (PUT /auth/users/{userId}/password)
	UpdatePassword(w http.ResponseWriter, r *http.Request, body UpdatePasswordJSONRequestBody, userId string)
	// list user policies
	// (GET /auth/users/{userId}/policies)
	ListUserPolicies(w http.ResponseWriter, r *http.Request, userId string, params ListUserPoliciesParams)
	// detach policy from user
	// (DELETE /auth/users/{userId}/policies/{policyId})
	DetachPolicyFromUser(w http.ResponseWriter, r *http.Request, userId string, policyId string)
	// attach policy to user
	// (PUT /auth/users/{userId}/policies/{policyId})
	AttachPolicyToUser(w http.ResponseWriter, r *http.Request, userId string, policyId string)

	// (GET /config/version)
	GetVersion(w http.ResponseWriter, r *http.Request)

	// (GET /healthcheck)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// chi-middleware.tmpl based on https://github.com/deepmap/oapi-codegen/tree/master/pkg/codegen/templates

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetCredentials")
	defer task.End()

	var err error

	// ------------- Path parameter "accessKeyId" -------------
	var accessKeyId string

	err = runtime.BindStyledParameter("simple", false, "accessKeyId", chi.URLParam(r, "accessKeyId"), &accessKeyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter accessKeyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentials(w, r, accessKeyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetExternalPrincipal operation middleware
func (siw *ServerInterfaceWrapper) GetExternalPrincipal(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetExternalPrincipal")
	defer task.End()

	var err error

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExternalPrincipalParams

	// ------------- Required query parameter "principalId" -------------
	if paramValue := r.URL.Query().Get("principalId"); paramValue != "" {

	} else {
		http.Error(w, "Query argument principalId is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "principalId", r.URL.Query(), &params.PrincipalId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter principalId: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExternalPrincipal(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListGroups")
	defer task.End()

	var err error

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:CreateGroup")
	defer task.End()

	// ------------- Body parse -------------
	var body CreateGroupJSONRequestBody
	parseBody := r.ContentLength != 0
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'CreateGroup' as JSON", http.StatusBadRequest)
			return
		}
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroup(w, r, body)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DeleteGroup")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, groupId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetGroup")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, groupId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListGroupMembers operation middleware
func (siw *ServerInterfaceWrapper) ListGroupMembers(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListGroupMembers")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupMembersParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupMembers(w, r, groupId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroupMembership(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DeleteGroupMembership")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroupMembership(w, r, groupId, userId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AddGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) AddGroupMembership(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:AddGroupMembership")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddGroupMembership(w, r, groupId, userId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListGroupPolicies operation middleware
func (siw *ServerInterfaceWrapper) ListGroupPolicies(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListGroupPolicies")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupPoliciesParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupPolicies(w, r, groupId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DetachPolicyFromGroup operation middleware
func (siw *ServerInterfaceWrapper) DetachPolicyFromGroup(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DetachPolicyFromGroup")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DetachPolicyFromGroup(w, r, groupId, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AttachPolicyToGroup operation middleware
func (siw *ServerInterfaceWrapper) AttachPolicyToGroup(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:AttachPolicyToGroup")
	defer task.End()

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "groupId", chi.URLParam(r, "groupId"), &groupId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter groupId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachPolicyToGroup(w, r, groupId, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListPolicies operation middleware
func (siw *ServerInterfaceWrapper) ListPolicies(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListPolicies")
	defer task.End()

	var err error

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPoliciesParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPolicies(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreatePolicy operation middleware
func (siw *ServerInterfaceWrapper) CreatePolicy(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:CreatePolicy")
	defer task.End()

	// ------------- Body parse -------------
	var body CreatePolicyJSONRequestBody
	parseBody := true
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'CreatePolicy' as JSON", http.StatusBadRequest)
			return
		}
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePolicy(w, r, body)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeletePolicy operation middleware
func (siw *ServerInterfaceWrapper) DeletePolicy(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DeletePolicy")
	defer task.End()

	var err error

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePolicy(w, r, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetPolicy operation middleware
func (siw *ServerInterfaceWrapper) GetPolicy(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetPolicy")
	defer task.End()

	var err error

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicy(w, r, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdatePolicy operation middleware
func (siw *ServerInterfaceWrapper) UpdatePolicy(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:UpdatePolicy")
	defer task.End()

	var err error

	// ------------- Body parse -------------
	var body UpdatePolicyJSONRequestBody
	parseBody := true
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'UpdatePolicy' as JSON", http.StatusBadRequest)
			return
		}
	}

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePolicy(w, r, body, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ClaimTokenId operation middleware
func (siw *ServerInterfaceWrapper) ClaimTokenId(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ClaimTokenId")
	defer task.End()

	// ------------- Body parse -------------
	var body ClaimTokenIdJSONRequestBody
	parseBody := r.ContentLength != 0
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'ClaimTokenId' as JSON", http.StatusBadRequest)
			return
		}
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimTokenId(w, r, body)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListUsers")
	defer task.End()

	var err error

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "id" -------------
	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "email" -------------
	if paramValue := r.URL.Query().Get("email"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "email", r.URL.Query(), &params.Email)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter email: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "external_id" -------------
	if paramValue := r.URL.Query().Get("external_id"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "external_id", r.URL.Query(), &params.ExternalId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter external_id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:CreateUser")
	defer task.End()

	// ------------- Body parse -------------
	var body CreateUserJSONRequestBody
	parseBody := r.ContentLength != 0
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'CreateUser' as JSON", http.StatusBadRequest)
			return
		}
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r, body)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DeleteUser")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, userId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetUser")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListUserCredentials operation middleware
func (siw *ServerInterfaceWrapper) ListUserCredentials(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListUserCredentials")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserCredentialsParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserCredentials(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateCredentials operation middleware
func (siw *ServerInterfaceWrapper) CreateCredentials(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:CreateCredentials")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCredentialsParams

	// ------------- Optional query parameter "access_key" -------------
	if paramValue := r.URL.Query().Get("access_key"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "access_key", r.URL.Query(), &params.AccessKey)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter access_key: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "secret_key" -------------
	if paramValue := r.URL.Query().Get("secret_key"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "secret_key", r.URL.Query(), &params.SecretKey)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter secret_key: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "read_only" -------------
	if paramValue := r.URL.Query().Get("read_only"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "read_only", r.URL.Query(), &params.ReadOnly)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter read_only: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCredentials(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteCredentials operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentials(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DeleteCredentials")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "accessKeyId" -------------
	var accessKeyId string

	err = runtime.BindStyledParameter("simple", false, "accessKeyId", chi.URLParam(r, "accessKeyId"), &accessKeyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter accessKeyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCredentials(w, r, userId, accessKeyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetCredentialsForUser operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialsForUser(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetCredentialsForUser")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "accessKeyId" -------------
	var accessKeyId string

	err = runtime.BindStyledParameter("simple", false, "accessKeyId", chi.URLParam(r, "accessKeyId"), &accessKeyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter accessKeyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentialsForUser(w, r, userId, accessKeyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteUserExternalPrincipal operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserExternalPrincipal(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DeleteUserExternalPrincipal")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteUserExternalPrincipalParams

	// ------------- Required query parameter "principalId" -------------
	if paramValue := r.URL.Query().Get("principalId"); paramValue != "" {

	} else {
		http.Error(w, "Query argument principalId is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "principalId", r.URL.Query(), &params.PrincipalId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter principalId: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserExternalPrincipal(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateUserExternalPrincipal operation middleware
func (siw *ServerInterfaceWrapper) CreateUserExternalPrincipal(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:CreateUserExternalPrincipal")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateUserExternalPrincipalParams

	// ------------- Required query parameter "principalId" -------------
	if paramValue := r.URL.Query().Get("principalId"); paramValue != "" {

	} else {
		http.Error(w, "Query argument principalId is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "principalId", r.URL.Query(), &params.PrincipalId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter principalId: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUserExternalPrincipal(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListUserExternalPrincipals operation middleware
func (siw *ServerInterfaceWrapper) ListUserExternalPrincipals(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListUserExternalPrincipals")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserExternalPrincipalsParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserExternalPrincipals(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateUserFriendlyName operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserFriendlyName(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:UpdateUserFriendlyName")
	defer task.End()

	var err error

	// ------------- Body parse -------------
	var body UpdateUserFriendlyNameJSONRequestBody
	parseBody := true
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'UpdateUserFriendlyName' as JSON", http.StatusBadRequest)
			return
		}
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserFriendlyName(w, r, body, userId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListUserGroups operation middleware
func (siw *ServerInterfaceWrapper) ListUserGroups(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListUserGroups")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserGroupsParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserGroups(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdatePassword operation middleware
func (siw *ServerInterfaceWrapper) UpdatePassword(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:UpdatePassword")
	defer task.End()

	var err error

	// ------------- Body parse -------------
	var body UpdatePasswordJSONRequestBody
	parseBody := true
	if parseBody {
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "Error unmarshalling body 'UpdatePassword' as JSON", http.StatusBadRequest)
			return
		}
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePassword(w, r, body, userId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// ListUserPolicies operation middleware
func (siw *ServerInterfaceWrapper) ListUserPolicies(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:ListUserPolicies")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUserPoliciesParams

	// ------------- Optional query parameter "prefix" -------------
	if paramValue := r.URL.Query().Get("prefix"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "prefix", r.URL.Query(), &params.Prefix)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter prefix: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "after" -------------
	if paramValue := r.URL.Query().Get("after"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "after", r.URL.Query(), &params.After)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter after: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "amount" -------------
	if paramValue := r.URL.Query().Get("amount"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "amount", r.URL.Query(), &params.Amount)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter amount: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "effective" -------------
	if paramValue := r.URL.Query().Get("effective"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "effective", r.URL.Query(), &params.Effective)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter effective: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserPolicies(w, r, userId, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DetachPolicyFromUser operation middleware
func (siw *ServerInterfaceWrapper) DetachPolicyFromUser(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:DetachPolicyFromUser")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DetachPolicyFromUser(w, r, userId, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// AttachPolicyToUser operation middleware
func (siw *ServerInterfaceWrapper) AttachPolicyToUser(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:AttachPolicyToUser")
	defer task.End()

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", chi.URLParam(r, "userId"), &userId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "policyId" -------------
	var policyId string

	err = runtime.BindStyledParameter("simple", false, "policyId", chi.URLParam(r, "policyId"), &policyId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter policyId: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachPolicyToUser(w, r, userId, policyId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:GetVersion")
	defer task.End()

	ctx = context.WithValue(ctx, Jwt_tokenScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx, task := trace.NewTask(r.Context(), "api:HealthCheck")
	defer task.End()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/credentials/{accessKeyId}", wrapper.GetCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/external/principals", wrapper.GetExternalPrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/groups", wrapper.CreateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/groups/{groupId}", wrapper.DeleteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/groups/{groupId}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/groups/{groupId}/members", wrapper.ListGroupMembers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/groups/{groupId}/members/{userId}", wrapper.DeleteGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/groups/{groupId}/members/{userId}", wrapper.AddGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/groups/{groupId}/policies", wrapper.ListGroupPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/groups/{groupId}/policies/{policyId}", wrapper.DetachPolicyFromGroup)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/groups/{groupId}/policies/{policyId}", wrapper.AttachPolicyToGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/policies", wrapper.ListPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/policies", wrapper.CreatePolicy)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/policies/{policyId}", wrapper.DeletePolicy)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/policies/{policyId}", wrapper.GetPolicy)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/policies/{policyId}", wrapper.UpdatePolicy)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/tokenid/claim", wrapper.ClaimTokenId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/users/{userId}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users/{userId}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users/{userId}/credentials", wrapper.ListUserCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/users/{userId}/credentials", wrapper.CreateCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/users/{userId}/credentials/{accessKeyId}", wrapper.DeleteCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users/{userId}/credentials/{accessKeyId}", wrapper.GetCredentialsForUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/users/{userId}/external/principals", wrapper.DeleteUserExternalPrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/users/{userId}/external/principals", wrapper.CreateUserExternalPrincipal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users/{userId}/external/principals/ls", wrapper.ListUserExternalPrincipals)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/users/{userId}/friendly_name", wrapper.UpdateUserFriendlyName)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users/{userId}/groups", wrapper.ListUserGroups)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/users/{userId}/password", wrapper.UpdatePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/users/{userId}/policies", wrapper.ListUserPolicies)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/users/{userId}/policies/{policyId}", wrapper.DetachPolicyFromUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/auth/users/{userId}/policies/{policyId}", wrapper.AttachPolicyToUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/config/version", wrapper.GetVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthcheck", wrapper.HealthCheck)
	})

	return r
}

// inline.tmpl based on https://github.com/deepmap/oapi-codegen/tree/master/pkg/codegen/templates

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdX2/cOJL/KoTugJ0FNLaTDRa3PuyDxx7nfDebCeIk8zAODFpid3MikRqSstMX+Lsf",
	"WEVKlES1uu1u/8nlKXFL4p9iVbHqV8Xi1ySTZSUFE0Ynh1+TiipaMsMU/PWWzrmghktxNDNM2Z9oUcib",
	"n8vKLD/SombJoVE1S5Oc6Uzxyr6aHCZnIucZNUwTs2BEG6oMF3NSSS4MmUkFPytmaiVYTrhhpd4jZ/Yf",
	"UtbakCtGtFSG5eRqSSjRFcv4jGekGV1KqMhdK7qSQjOiF7IucsJFVtQ5I1IUS2IWUjNiFtSQTJaMUDsL",
	"+Owigf9fJOTaToNwgUPFXguuzR55v+CacE1qzXIYddWQIyUU5ybYF2N/t/9juSZG4nTJTMmyM3SYu+tG",
	"qpwpP3PsLUkTbkn3Z83UMkkTQUuWHOIokzTR2YKV1C6AWVb2gTaKi3lye5uGq1TKWhj7Vnc9znEUbj1E",
	"XV4xReTM9Q8TZ+qaKU9EXBq7JM38jSS5pXzJBSMLeUNKKpaW+nVhYNo511VBl6MTwaGFM8nZjNaFSQ5f",
	"HBykSUm/8LIu4S/7Jxf4548vUj9nLgybM9Wb9FvFZvzLHXmzgo+RRWhR9JgSuREX9IabRcO7Va0qy1py",
	"Rma8MMyuhSfGGAWwq5VreZsmnp9B/o6lmBU8gxXNpDAMF5dWVWHnwKXY/0PbWX0NGv13xWbJYfJv+61k",
	"7+NTvf+zUlJhR12qND3dpskbaU5lLfLd9/qOaVmrjJE30hDs8zZNzoEX8aOdD+FMGKYELQj2StyLafJB",
	"0NospOL/yx6AEp3ebtPkIy14Dj08EB3aDj0Jbj2nIisWlJfv5WcmzoAclZIVU4Yjo7IvFVdMX9KI8vkg",
	"+BfycyWzhVV/mmVS5DpJk5lUpX3fivXfXyVDKU8TY/u75Hlc7yn2Z82VXZ3f2zfTcCyfmkbl1R8MuftY",
	"sZwJw2mhh/OgWca0vvzMlvFe0yRTDKh0mVPDtjpZxWh+abetYavvld2iZsTYHQnHSD6zpVXOitmxZQZV",
	"tG3jR9j67KxgoKCPXG9XUhaMigH1utPuT3KCir9wbYaUbPfKKZZsNTlSAZSo/QhU8NTX4XLeNgOlStHl",
	"YJrBmNqOJmb3GzeLc5YpZh6KW/aeHrukiQYSXLYzjk631kw5UuSsUszus7nfhteYE3yP22V/TmdlJZWh",
	"wpAfcV4zXtht2k4JV5hwoQ2jud2U7R7tBkNuFtzSV5N2SHvkiNSC/2nJBAs940w1m7v9cI+cCVJRrW+k",
	"yn+8otYEshravoyK19tKVww+YiXlRUC7ET3Vl7QhXftM01I1xqnN7tDlzJJpTecRMr63Q7XfEPfK9JB9",
	"W9Huv+Du+VZxkfGKFsOhjEhGwCqru/cvpskYCfpjeFyFNCTJ1tTSayXrKiIayO8cpEFIQyolr3nO8pRw",
	"a7cWhWXSORNWxNGnyqS4ZuiU2U/n/JoJYgWPcGEkoWRuuyI8t+zRpeMOVVqnpQjPeM0S9hcTZKcAYA4R",
	"/vYW+TpNeZ0AbaVEWRWimWhc00VdUvGj1aP0qmBAwmmJgu7X2WVhwY/da0OW3ha9djLJEWmFKT2uhKIY",
	"TUmlbzUNxxWb0dvOsIfqtv2clCxbUMF1GbrVihnF2TUjFJCAxi8fit6C6stSqijrur2acHRvrWTfLJhZ",
	"OLzjTYNTWJPgmvLCLmV8ry/pl8uKqcsquoP8C/30AEVgwk5Ak4oBRAKtNu77QUzQBftiLuVsppmJzQUh",
	"mQF9uniLnDUONyI1DsjRxCwrntGiWMIGbjdu9PUR/WkwpAbzqa80+7NmwpCjt2fEfmlbDPsCHeqRJWr/",
	"D+gArSpGwfVvgSUH+LCcBJOMKqGAbbsEeNNQFqak/UADfGEVeXt83DBNb2HTgMPD9YiyuCx4towZwMVw",
	"+O+8+nBUR/vTeq9KFsjiVGs+F7i8YMxV0EGUTDvcb1ZvA2lM77UI0PiItaGGlc5VX0sjnTdf3MLanuFH",
	"LyZUlNtH2v7G1+5Yipx7HUVz/L81Ujqmmh/rYErdYUTAI2zQuRFSkR/Y3nwvJWfVUZ4rpvVfwTGnZVUA",
	"xZvf7TRe/OPl3ou//8fewd6L/b+9TNLgh5f2h0+3o9N63I3EicXW7LvzkHG6JD5hhvJCE3ola4MOx5eK",
	"gR+njaozUyvm7Z6WGCSjwtp+M1mL3KuRgn5mp+ckl1lt+4KBDfcamnn6jXPFCk5Nk2wdjpumbsu4A7b7",
	"tcImSdOVBvG8WTCBaqWRDAKIGQud25bsbDZjiLEyYXXq7wgkJ7Y/sQxWqqO7Abicdl9c48EnqadtjAU+",
	"aBZx53aoA8Fvja4uE5laVoblb50bvFLVU0GaDxrH2e68lGCTnfFcLcGzHfbpnKcxPGWmOBN5sbwcU90d",
	"HW1dR4T2nWMkmN2LqOLF0in5uAJv1rZHZ9sePtwjPwEmIAXhVql1JCnq7G7ucwAOsa4z0XQxxA+GCznG",
	"eeOuRsMmA9ezdTYbGMSSWzODuzsj2q4JWmfOEvODjRLrKfPdG7eIQ1dLXHOz0jAHPmxCaLqxzsFmv+bI",
	"PY5+LbRkJ0nAIwdmtqxBs0zWwhC/zHvEroKzdEXeUF5ZEwaAgX7zHhKAxmkhra/AzaKVmabpOBb4hMSD",
	"nEJcdgVOByAI112QruTiFybmZhFuXSsAKBjdmNQ8rhECO8bWTBDbWih3PS0QE80J4ervh2spo49MaS7F",
	"sRQzPh+O4xofT+++/sVhH4hp14qb5bmlJDb8x425hFCS/eOKUcXUqZ/ef//23gdvQSDgaTvfhTEVBta4",
	"mMkhK/v4Hgqi9TS9g1tSQecMAAGlU0RhdGqF0AchQK7B47AESBPDjbWjE2fKDZpO0pZEycHei70DS1RZ",
	"MUErnhwmf9s72DsAZMMsYN77ton9oMf9r+i3/Q9bnuW39pV5zFd/B+FyFK5wvLk3V7WWGQfUETRMkBAR",
	"tI/uNhdV3Uhq8LTN9ZC1ca9QEg3RkEY+wN+kXIBzXhTB4PzY9sgbaVxyiMsEuOay1sWyjSj4EAKYDzdB",
	"AKEdk9cOsUhEStg1mKKyni+cGrJmiPWBbesib7JR/KcXCSnoFSvQWOeaLGlZOICDiRyzSNrtoVGu0Cmh",
	"ZFYLMC7BEMrJnJmAUFbzNYGeszw5TF53nie99IOXBwdbCzzHQ2qRQHTWDei9Ongx1nQz1v1+9PzVwavp",
	"j5o0BxiCS0WZ+ijMTQAdUpclVcvk0MpHKAJWSukc/Fs7NnBiw+Sq379ikogVwSBLpmX7JNRkGEEbTxyx",
	"raMMe0tmv/LxBx1I72D1h9GKHfJAJDQyXH8/AVKFAZSHYYNXLw+GOs5I6ZOd/qyZNnpLDIO9XFlPvj9j",
	"crUkEPLqsFBrpmKWA1Mc7KpilLkGGUiu/TtzF+5Nk9tBi2TjB3vkKMtYZXQIhrcDtuY6an+rVVXTSGsY",
	"BYo9sFeH3bxvYdJIJiEAyFZXO2tiCeg1zRYEQgJBJw4qaYIVTZohdhECqW1j7qNgig6Qic7DzmDQTTAC",
	"3CrARuAuR6lY3n0nsJR6jVQa7AK/NM+SAR/FuLt9ZX+QhnebbvANZpVu9gnmEd5+2qGeamNUEf2EkdEC",
	"nt5RL21BeQDjz/2aDXcaqSPiCe49s5Il2I0Lj3ZNL+/MtyEHUHnkSubLSM5tK6o9AXIBlI6seXmkY/g6",
	"UhZwAdLGtGecFU1ku4mupK0wI7Lgfdo6CPjwvC8vXEN8h+Ukr5WPfmtm6opoY4XZSHR+LU04mIveHMfw",
	"j/3mIjnKSy70RZKSi+S8rpiybpP7+4Rds8JOGf62JLtIPnJ2Az8gXZwdCzPTHV1DkAWRVrTgc9F65rhI",
	"kY88auM+vruOwJm/9mHzrpI4bh+6zYNp85PMl9sVuwaCuh2mw75EYdteZ6Py/YAmx8E/pj8Is3O3oDwc",
	"h8/dWva0R2+z3/8K/zovMGcFi+FcJ/C79pkje+Q9/Qx/OvzGtYHAnLV5w1x+zNACni+pyRYA6n3hGqLY",
	"qBXOTqy/FniAbaI2agoYmGVlromuwYye1ffwnHCiI7Jw0j4c2suvhtRB2cYm82B4xXLvWfk4OIMxxkmn",
	"MQKPC8hZCAXsjmXeh7uVC+BHt6uzxsRKI2ZiR0V3bDSXSOVD2bjnnPT3lmpBNYCx8b2oUfHtztLMwbZ7",
	"zRSfLVuoAp/dUO00dn4vgGCEx1+7J8muDa0noIS35P6PysW04++Y/V5uWaup90tWXrkzXJMy6X0ogB9X",
	"IXYdMW348AyjDqsdu3RDz24wrnVcuwaKG7h3EJkYeHceu+85d0EsaKABJhrqqIaZVK1rr5fasLKhLoRt",
	"duBJxkcy4kgyMgDjpyZ8167u6bP+C9l5hefq3vjuv/qQ0Gr3FfXDE/JiSdks4JPRnvtfrUaZMHzfsVJe",
	"g03R6EmM1PbOf65UntgP+cFrsL82inPC6oWuOhYvhC/skHIcQpsIvQ1T2InZgq82itvX1jKPy+b1qI38",
	"bE1kUoZ0eCC+TqMtIYdtJiBpUtWx/Nw8H7I7pCg8BrPTPG+N73syOs3zSS4/GryTxFGKURbHET9bBqd5",
	"vgZ3jyvXJoy9iW3qPyLUGJotcMXX9yAn7dMOLhf4iXE7VeRB6MHbpJEwA0KX3gjFfMah9dhmsk65od4I",
	"HDQU9UOx+52Yme2Q1zQ0aVYMuh1MI96Bs6R9i7Z9LO5gl6HJ62NWpiDxsxFyCP0L8u6no+PB0T3g7i0Y",
	"pm8dX66wTN+2aRvfTdP9IG07Ypw6lriXWfoYOjGwY8MsnUc3ZP1g9r/icYVJEBeUK+BtuBIrrdi4nnUd",
	"rbup59Bn6RTIdpBb2yKy0qmS5SiGG3ltLXPVcSn288zxXDuFzmI/MIYVt1Y9E23HXjV9rt7YdtiQp9FI",
	"2SZPY4vIeO/lCEcfDV9ayzZ1/NyYVs+Xn3EKwTJPhbjWNkbpwBTdeU5L29Fds1qmLc4A+pw0PUea/G57",
	"Prztudrs/G5xrm9xVluwOLdlQK40HddI6HFHUreU0dMXkV4w1eWhOL7FGGybpdKu9gYZOBAlDTJwHF1b",
	"57/Jr7ZC2fA9Dswt5NmJJj9YQdF/dUXdlDvn4o9vXySn56d1URzBJoc5O6fn7xjNf1PcsKOiCH9zfzKT",
	"rUjdcaTaMHen89UGquopKiVcsbfNmehY6pA7Lbub3CF/FLd7AMSajLtMIgp7jekVVCkH05qhX+7t7kbX",
	"o2UTVX55p2yttZ1Rn1HU6LWuhR5a5RsmiDTK4lGSisbE5CR4upYjWnlH9NuImYxx0J3zitZgnKiJPtj5",
	"tgrL+u+eucqfMzPGyK/9o2Tndt2U7n1G2UPj7D8NvWwVMPlQ5WhVDjTmuCj94CJ5EBoJbczwIB4E8aBx",
	"j6l4we3mB4Xv3ckMlZqtNHyfueghbcak70Pw9AlYWwffrrW1BcHHpZw2nuBQMs/3s4LyEg5ERx3C0xir",
	"RgzysJjvblik08V4Ln//qN1nK0I5gWl6dXyw++rH1231Y/bYLAFzJ5QgMc5O0kYv9kdpzVRaKEatmnUU",
	"G2chyKPcAOikReFzL3eMdG49w3NosTVfNlXiRlHLFhXpFFIBH8BIBYe/21lIX4TI70S19TU06VSqgRax",
	"+MT3FNMnl2IKh7fiUCo8ej44ajp6B0LsODAWIG4U52SxqA2bx5JBE8G/QQWZHK0rLnydsp/tKleKa/af",
	"sPRO+18VrFfQ7Nfzc+KqXoxdwRCW+ZmwjB8lORdE4Ulg0bUeS8ZdA4jGyjzbgaH7in2AJtNCS9QHk4Ay",
	"IrF4rJPmJReYUgh63G8Q/7xI4NFFgsWUoJzRPy8Sr2xWnuHECkibwcBh3a0OGDy1STQf2XF2yaTX3hw2",
	"Vs/31/XNuKcb9aeAobjWBo0F1bCwDJZm1jHtVNq6WrpqWPatgEGQeX81C6ZuuGYp6qPBC/dDyj+40m4x",
	"nBwKOu3GKO/UeNvxAVusSzXUce87RXNEV+4DvLZv73XUB2ZhPJh78HFb7sEj4vM1stVK72CtEw8tMO8k",
	"oQsJRdO7N8TnQS2fndjVXspauaNpeCvXIwD2cWk9aZ6tBdaDHv1mjgDHuenOSP0qTroz+4wf/53yFjuO",
	"X4r7BFop3knU5IebBVP+1oWcKd45chNwv3JFKZpndz9u+PCb+p1jA3GZeY0Pkh3b12O29bOLCYyJ2XRE",
	"4C4HfkY2g7Au4Ib4Uee6G+3tfN5WGCUYaoC6puupA8jqAJnvhShA6gNkJgpWjeuEOx/16MzRl6sRYYHC",
	"OLrRu0KrH+LYMmwz2tvOIJWVhQd/Gb70PV2tVydxDCUIalk+z5MSvsbw/Wol3vFI40r8QrCbTh3TuF5q",
	"PPmSzxdtZlmrCFwdZrja6zNb3q2CKdoXHTeoqYXlpwwuMuPNNS/BEKQKRmC/YWVlnH3Tve3V3wxFFBW5",
	"LP2tI3buV9IscDJG4mDKXv1lvOEmNM5CpbqB6m7KpjiExpWz7dbB9WEBV/ekGUsL2mBXnuJcQ6VdXxyM",
	"i2v5GRH/iqmZVKVLEsy88XQfp36lwjvuv5KsVbKxczHc9DGK3tctA2yGw57NgvLhViaCSwQzKhAS8RRU",
	"cOde5/7A2Fja+wqjdwDPaKFZ5KLKTzuEKJ52TdpHxApW6uY1rMRh9egpMGFa6TZnyb1baE2ztpfeUd4t",
	"qaRHABtWapGT/itrQQ/Hncrc3wgCMWE/TDgpHe76S4f/+rz2F91huWgF80HZJOAr9EhWHjEPOgkvas1b",
	"VNo7SdsqAn4q1ahvPnztgUqCf8OFwJ06e1BPPt1RcfGexh+pNd7q+jHAdI2q4xE1FqmT7bTZc9RfkdkA",
	"Qui0QeQxOHuRmuBrFALfGkdtq6J464iNhcDW4JEXa/GI9xW2lB6/oVH2oCXlj91RjGbuNGAkvELHQEau",
	"YP4K8LhmGrDVBipgf8WNAx72GSzud/QnfkPCGAY05HP9/HCgyCRgt1yLIx8aBB9cPbczhGpVTr61F7up",
	"hU2RIbppFM3Zs9a/7zYZzZhfXZqralIkt+AIYWtWT5wG966NZbr337tH7kT3lqnBiq++a6r7euTGqTWS",
	"5SNWj58aHjq6ob36Z+6cxN4zTn7H6P4snOf6qMOaN5KExcTwE4f89erY8UEF3FGB2mnR2+Bq693caPKs",
	"LzKxIr/qMpP2+Xez4iEuNHncSNKKa1Ae1EKownsTd2scRE98+e53lzvYdLH+ya9eqSGfkOKP90VgyGe8",
	"h1XtEqy5fd2zGuZ4sXa0BV0CLV5Cza/DSxab+E6TDOF0cBPOLIp43c2mFmvOFcuMOwtpFgquObRubbPD",
	"uhevmN3lNDESA5btcDTBwI8LKfnu2pZj/babhbdDO9nmY1h/JhXOFW7xsb5vD+9P4xt6G75tB+4CVE+l",
	"buj3Oks7qbMEOm9lraXwjWd1Tmgk4IsCBbKfg2RkZkIJSAUi77hqXPJTItucetcNrLHx1XsmBX/0WI8X",
	"y/uGlp9T1anHtbnuV+Z0q1bXtmucRlGUtmZIW8H8yVQ4HctPH771vb7pE4jDPWh105WY4BOsbRrn5aPB",
	"O//fK5uOH+fJ4NL8/eCO/KhjMWfG5wH6VyMZAR+bRzvbKrt3/a+KdQyv0O9NwH7rKYJkcDRZMFqYRbZg",
	"2edRgsDT9pK1oHmuSV0hmFcLYeWxT6n/gvaPof11VOwbeexIB8vMslpxs0wOf//UTmARtPnptvfe1+SP",
	"G3MJJSLsV1Y94GBRfXV7cwekewayF9UkTWpVJIfJPq34/vWL5PbT7f8FAAD//xq6lLoXogAA",
}

// GetSwaggerSpecReader returns a reader to the Swagger specification corresponding to the generated code in this file.
func GetSwaggerSpecReader() (io.Reader, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	return zr, err
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.T, error) {
	zr, err := GetSwaggerSpecReader()
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	swagger, err := openapi3.NewLoader().LoadFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
